<?php
$mx_states = array(
  array('id' => 'MEX-AGS','value' => 'AGS', 'label' => 'Aguascalientes (AGS)'),
  array('id' => 'MEX-BCN','value' => 'BCN', 'label' => 'Baja California Norte (BCN)'),
  array('id' => 'MEX-BCS','value' => 'BCS', 'label' => 'Baja California Sur (BCS)'),
  array('id' => 'MEX-CAM','value' => 'CAM', 'label' => 'Campeche (CAM)'),
  array('id' => 'MEX-CHIS','value' => 'CHIS', 'label' => 'Chiapas (CHIS)'),
  array('id' => 'MEX-CHIH','value' => 'CHIH', 'label' => 'Chihuahua (CHIH)'),
  array('id' => 'MEX-COAH','value' => 'COAH', 'label' => 'Coahuila (COAH)'),
  array('id' => 'MEX-COL','value' => 'COL', 'label' => 'Colima (COL)'),
  array('id' => 'MEX-DF','value' => 'DF', 'label' => 'Distrito Federal (DF)'),
  array('id' => 'MEX-DGO','value' => 'DGO', 'label' => 'Durango (DGO)'),
  array('id' => 'MEX-GTO','value' => 'GTO', 'label' => 'Guanajuato (GTO)'),
  array('id' => 'MEX-GRO','value' => 'GRO', 'label' => 'Guerrero (GRO)'),
  array('id' => 'MEX-HGO','value' => 'HGO', 'label' => 'Hidalgo (HGO)'),
  array('id' => 'MEX-JAL','value' => 'JAL', 'label' => 'Jalisco (JAL)'),
  array('id' => 'MEX-EDM','value' => 'EDM', 'label' => 'México - Estado de (EDM)'),
  array('id' => 'MEX-MICH','value' => 'MICH', 'label' => 'Michoacán (MICH)'),
  array('id' => 'MEX-MOR','value' => 'MOR', 'label' => 'Morelos (MOR)'),
  array('id' => 'MEX-NAY','value' => 'NAY', 'label' => 'Nayarit (NAY)'),
  array('id' => 'MEX-NL','value' => 'NL', 'label' => 'Nuevo León (NL)'),
  array('id' => 'MEX-OAX','value' => 'OAX', 'label' => 'Oaxaca (OAX)'),
  array('id' => 'MEX-PUE','value' => 'PUE', 'label' => 'Puebla (PUE)'),
  array('id' => 'MEX-QRO','value' => 'QRO', 'label' => 'Querétaro (QRO)'),
  array('id' => 'MEX-QROO','value' => 'QROO', 'label' => 'Quintana Roo (QROO)'),
  array('id' => 'MEX-SLP','value' => 'SLP', 'label' => 'San Luis Potosí (SLP)'),
  array('id' => 'MEX-SIN','value' => 'SIN', 'label' => 'Sinaloa (SIN)'),
  array('id' => 'MEX-SON','value' => 'SON', 'label' => 'Sonora (SON)'),
  array('id' => 'MEX-TAB','value' => 'TAB', 'label' => 'Tabasco (TAB)'),
  array('id' => 'MEX-TAMPS','value' => 'TAMPS', 'label' => 'Tamaulipas (TAMPS)'),
  array('id' => 'MEX-TLAX','value' => 'TLAX', 'label' => 'Tlaxcala (TLAX)'),
  array('id' => 'MEX-VER','value' => 'VER', 'label' => 'Veracruz (VER)'),
  array('id' => 'MEX-YUC','value' => 'YUC', 'label' => 'Yucatán (YUC)'),
  array('id' => 'MEX-ZAC','value' => 'ZAC', 'label' => 'Zacatecas (ZAC)'),
);
?>
